
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 12 13:29:14 CST 2020
//----------------------------------------------------

package JFlexNCup;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int stringValue = 43;
  public static final int plus = 17;
  public static final int mod = 2;
  public static final int minus = 18;
  public static final int closingCurly = 14;
  public static final int openingBracket = 11;
  public static final int whileKeyword = 34;
  public static final int openingCurly = 13;
  public static final int closingBracket = 12;
  public static final int breakKeyword = 33;
  public static final int openingPar = 9;
  public static final int caseKeyword = 32;
  public static final int doKeyword = 35;
  public static final int comma = 15;
  public static final int trueValue = 46;
  public static final int inKeyword = 37;
  public static final int valAsignment = 8;
  public static final int forKeyword = 36;
  public static final int defaultKeyword = 41;
  public static final int lesserEquals = 6;
  public static final int elseKeyword = 30;
  public static final int returnKeyword = 39;
  public static final int integerValue = 48;
  public static final int functionKeyword = 40;
  public static final int arrowFunction = 7;
  public static final int greaterEquals = 5;
  public static final int EOF = 0;
  public static final int continueKeyword = 38;
  public static final int error = 1;
  public static final int equals = 3;
  public static final int nullValue = 42;
  public static final int times = 19;
  public static final int or = 26;
  public static final int colon = 28;
  public static final int ifKeyword = 29;
  public static final int ternary = 27;
  public static final int id = 47;
  public static final int greater = 22;
  public static final int closingPar = 10;
  public static final int numericValue = 44;
  public static final int and = 25;
  public static final int not = 24;
  public static final int lesser = 23;
  public static final int notEquals = 4;
  public static final int falseValue = 45;
  public static final int div = 20;
  public static final int switchKeyword = 31;
  public static final int semicolon = 16;
  public static final int power = 21;
}

